apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 6
  template:
    metadata:
      name: nginx-pods
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx
