apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432  # expose service port, exposed in inside cluster
      targetPort: 5432  # listen port from pod
  selector:
    name: postgres-pod
    app: demo-voting-app

