apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80  # expose service port, exposed in inside cluster
      targetPort: 80  # listen port from pod
      nodePort: 30004  # expose service port, exposed in outside cluster
  selector:
    name: voting-app-pod
    app: demo-voting-app

