apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicasets
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      name: nginx-pods
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
